---
# k8s/base/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ramydockerid/vote-backend:latest
          ports:
            - containerPort: 8880
          imagePullPolicy: Always
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
