---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base components
resources:
  - ../../base

namespace: vote-prd

patches:
  - path: backend-replicas-patch.yaml
  - path: ingress-patch.yaml
