---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base components
resources:
  - ../../base
  - backend-hpa.yaml
  - frontend-hpa.yaml

namespace: vote-stg

patches:
  - path: backend-replicas-patch.yaml
  - path: ingress-patch.yaml
