name: e2e-tests.yml
on:
  repository_dispatch:
    types: [ trigger-e2e ]

jobs:
  run-e2e:
    name: e2e test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Port-forward frontend and test with curl
        run: |
          echo "✅ Test 1: Valid vote - Cats"
          curl -s -o /dev/null -w "%{http_code}" -X POST "https://voteapp.dev.rch.domain-buy-5.com/vote?vote=Cats" | grep -q 200 || exit 1
      
          echo "✅ Test 2: Valid vote - Dogs"
          curl -s -o /dev/null -w "%{http_code}" -X POST "https://voteapp.dev.rch.domain-buy-5.com/vote?vote=Dogs" | grep -q 200 || exit 1
      
          echo "❌ Test 3: Invalid vote - Cat (typo)"
          curl -s -o /dev/null -w "%{http_code}" -X POST "https://voteapp.dev.rch.domain-buy-5.com/vote?vote=Cat" | grep -q 400 || exit 1
      
          echo "❌ Test 4: Invalid vote - Unicorn"
          curl -s -o /dev/null -w "%{http_code}" -X POST "https://voteapp.dev.rch.domain-buy-5.com/vote?vote=Unicorn" | grep -q 400 || exit 1
      
          echo "❌ Test 5: No vote param"
          curl -s -o /dev/null -w "%{http_code}" -X POST "https://voteapp.dev.rch.domain-buy-5.com/vote" | grep -q 400 || exit 1
      
          echo "🎉 All E2E tests passed!"
